---
jobs:
- name: test-unit
  public: true
  plan:
    - get: bosh-cpi-go
      trigger: true
    - task: test-unit
      privileged: true
      file: bosh-cpi-go/ci/tasks/test-unit.yml

- name: bump-deps
  plan:
  - in_parallel:
    - get: bosh-cpi-go
    - get: golang-release
    - get: weekly
      trigger: true
  - task: bump-deps
    file: golang-release/ci/tasks/shared/bump-deps.yml
    input_mapping:
      input_repo: bosh-cpi-go
    output_mapping:
      output_repo: bumped-bosh-cpi-go
  - in_parallel:
    - task: test-unit
      privileged: true
      file: bosh-cpi-go/ci/tasks/test-unit.yml
      input_mapping:
        bosh-cpi-go: bumped-bosh-cpi-go
  - put: bosh-cpi-go
    params:
      repository: bumped-bosh-cpi-go
      rebase: true

resources:
- name: bosh-cpi-go
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-cpi-go.git
    branch: master
    private_key: ((github_deploy_key_bosh_cpi_go.private_key))

- name: golang-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-package-golang-release.git

- name: weekly
  type: time
  source:
    start: 3:00 -0700
    stop: 4:30 -0700
    days: [ Saturday ]
    initial_version: true
